# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name_plural': 'Payments Received'},
        ),
    ]
