# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20160904_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='regNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
