# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20160904_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentIdFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ID Fee (Ksh)')),
            ],
        ),
    ]
