# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_studentidfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentidfee',
            name='accadmic_year',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='regNo',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
