# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20160904_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentidfee',
            old_name='accadmic_year',
            new_name='academic_year',
        ),
    ]
