# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160903_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idapplication',
            name='passport',
            field=models.ImageField(upload_to='img/passports', verbose_name='Passport Photo '),
        ),
    ]
