# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160903_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='idapplication',
            name='application_type',
            field=models.CharField(choices=[('F', 'First Time'), ('R', 'Replacement')], default='F', max_length=32),
        ),
    ]
