# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160904_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='idapplication',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
