# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_idapplication_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=13)),
                ('message', models.TextField(max_length=200)),
            ],
        ),
    ]
